import { DesignToken } from "@microsoft/fast-foundation";
import { AdaptiveDesignSystem } from "@adaptive-web/adaptive-web-components";
import { AllComponents } from "@adaptive-web/adaptive-web-components/all-components";
import { FASTRouter } from "@microsoft/fast-router";
import { AppMain } from "./app-main/app-main.js";
import { NotFoundPage } from "./pages/not-found-page/not-found-page.js";
import { SettingsPage } from "./pages/settings-page/settings-page.js";
import { AppPage } from "./components/app-page/app-page.js";
import { SFTComponents } from "./sft/custom-elements.js";
import { registerDraggableAnchor } from "./sft/components/anchored-region/examples/draggable-anchor.js";
import { registerAnchoredRegionPointer } from "./sft/components/anchored-region/examples/anchored-region-pointer.js";

FASTRouter;
AppMain;
AppPage;
NotFoundPage;
DesignToken.registerDefaultStyleTarget();
AdaptiveDesignSystem.defineComponents(AllComponents);
AdaptiveDesignSystem.defineComponents(SFTComponents);
registerAnchoredRegionPointer();
registerDraggableAnchor();